# Generated by Django 4.2.11 on 2026-06-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequently_bought_together',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shareasale', 'ShareASale'), ('clickbank', 'ClickBank'), ('cj', 'CJ Affiliate'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('button_text', models.CharField(blank=True, help_text="Optional custom text, e.g., 'Buy on Amazon'", max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_links', to='store.product')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
    ]
