# Generated by Django 4.2.11 on 2026-06-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand_productspecification_producthighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shareasale', 'ShareASale'), ('clickbank', 'ClickBank'), ('cj', 'CJ Affiliate'), ('dropship', 'Dropship Direct'), ('other', 'Other')], default='amazon', max_length=20),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('shareasale', 'ShareASale'), ('clickbank', 'ClickBank'), ('cj', 'CJ Affiliate'), ('dropship', 'Dropship Direct'), ('other', 'Other')], max_length=20),
        ),
    ]
