# Generated by Django 4.2.11 on 2026-06-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_parent_alter_product_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text="Check to display this subcategory directly on the parent's homepage card."),
        ),
    ]
