# Generated by Django 4.2.11 on 2026-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_affiliate',
            field=models.BooleanField(default=True, help_text='Enable to show the affiliate buy button.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, help_text='If checked, the product is displayed but the buy button is disabled.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
