# Generated by Django 4.2.11 on 2026-06-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_product_brand_productspecification_producthighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('bank', 'Bank Transfer'), ('stripe', 'Stripe / Card'), ('paypal', 'PayPal')], default='cod', max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Payment'), ('paid', '💳 Paid'), ('ordered', '📦 Ordered from Supplier'), ('shipped', '🚚 Shipped'), ('delivered', '✅ Delivered'), ('cancelled', '❌ Cancelled'), ('refunded', '↩️ Refunded')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Payment'), ('paid', '💳 Paid'), ('ordered', '📦 Ordered from Supplier'), ('shipped', '🚚 Shipped'), ('delivered', '✅ Delivered'), ('cancelled', '❌ Cancelled'), ('refunded', '↩️ Refunded')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='dropshipping.order')),
            ],
            options={
                'verbose_name': 'Status Update',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_image', models.URLField(blank=True)),
                ('supplier_url', models.URLField(blank=True)),
                ('supplier_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dropshipping.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Order Item',
            },
        ),
        migrations.CreateModel(
            name='DropProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_url', models.URLField(help_text='Direct product URL on AliExpress / supplier site')),
                ('supplier_cost', models.DecimalField(decimal_places=2, help_text='Cost YOU pay the supplier (in USD)', max_digits=10)),
                ('shipping_days_min', models.IntegerField(default=7)),
                ('shipping_days_max', models.IntegerField(default=21)),
                ('stock', models.IntegerField(default=999, help_text='Available stock (approximate)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this drop product')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drop_info', to='store.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dropshipping.supplier')),
            ],
            options={
                'verbose_name': 'Drop Product',
                'verbose_name_plural': 'Drop Products',
            },
        ),
    ]
