# Generated by Django 4.2.11 on 2026-06-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='dropproduct',
            name='allow_bank',
            field=models.BooleanField(default=True, verbose_name='Allow Bank Transfer'),
        ),
        migrations.AddField(
            model_name='dropproduct',
            name='allow_cod',
            field=models.BooleanField(default=True, verbose_name='Allow Cash on Delivery'),
        ),
        migrations.AddField(
            model_name='dropproduct',
            name='allow_paypal',
            field=models.BooleanField(default=True, verbose_name='Allow PayPal'),
        ),
        migrations.AddField(
            model_name='dropproduct',
            name='allow_stripe',
            field=models.BooleanField(default=True, verbose_name='Allow Stripe / Card'),
        ),
        migrations.AddField(
            model_name='dropproduct',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost per unit for this product', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='call_before_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='gate_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='leave_at_front_door',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
